package model;

public enum WorkType {
    OIL_CHANGE,
    BRAKE_FLUID_CHANGE,
    SPARK_PLUG_REPLACEMENT,
    AIR_FILTER_REPLACEMENT,
    ENGINE_DIAGNOSTICS,
    TIRE_REPLACEMENT,
    BATTERY_REPLACEMENT
}